import {
  b2Body,
  b2World,
  b2BodyDef,
  b2BodyType,
} from "../../lib/box2d-physics-engine/Box2D";

export class Player {
  private id: string;
  private body: b2Body;

  constructor(id: string, world: b2World) {
    // assign a universally unique identifier generated by the simulation
    this.id = id;

    // define the dynamic body
    const bodyDef: b2BodyDef = new b2BodyDef();
    bodyDef.type = b2BodyType.b2_dynamicBody;
    bodyDef.position.Set(0, 0);
    this.body = world.CreateBody(bodyDef);
  }

  getId(): string {
    return this.id;
  }
}
